# Generated by Django 2.2.17 on 2021-08-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('estado_civil', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('numero', models.IntegerField(null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.IntegerField(null=True)),
                ('tel_1', models.IntegerField(null=True)),
                ('tel_2', models.IntegerField(blank=True)),
            ],
        ),
    ]
