# Generated by Django 3.2.6 on 2021-08-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_auto_20210830_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobrecandidato', models.TextField(verbose_name='sobreCandidato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.usuario')),
            ],
        ),
    ]
