# Generated by Django 3.2.6 on 2021-08-30 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidato.usuario'),
        ),
    ]
