# Generated by Django 3.2.6 on 2021-08-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_alter_cadastro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='nome',
        ),
    ]
