# Generated by Django 3.2.6 on 2021-08-31 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0004_alter_sobre_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('inicio', models.DateField(null=True)),
                ('fim', models.DateField(null=True)),
                ('local', models.CharField(max_length=50)),
                ('atividades', models.TextField(null=True, verbose_name='atividadesOuConquistas')),
                ('comprovante', models.FileField(null=True, upload_to='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=50)),
                ('data', models.DateField(null=True)),
                ('local_curso', models.CharField(max_length=50)),
                ('duracao_horas', models.IntegerField()),
                ('certificado', models.FileField(null=True, upload_to='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.usuario')),
            ],
        ),
    ]
