# Generated by Django 3.2.6 on 2021-08-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0004_auto_20210827_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
