# Generated by Django 3.2.6 on 2021-08-25 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0005_alter_sobre_sobrecandidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobre',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sobre',
            name='sobrecandidato',
            field=models.TextField(),
        ),
    ]
