# Generated by Django 3.2.6 on 2021-08-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_cadastro_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.cadastro'),
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.cadastro'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.cadastro'),
        ),
    ]
