# Generated by Django 3.2.6 on 2021-08-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0006_auto_20210825_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
