# Generated by Django 3.2.6 on 2021-08-30 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0006_auto_20210827_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('numero', models.IntegerField(null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.IntegerField(null=True)),
                ('tel_1', models.IntegerField(null=True)),
                ('tel_2', models.IntegerField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='experiencias',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.DeleteModel(
            name='Experiencias',
        ),
        migrations.DeleteModel(
            name='Sobre',
        ),
    ]
