# Generated by Django 3.2.6 on 2021-08-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0007_delete_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('registro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='candidato.registro')),
                ('sobrecandidato', models.TextField()),
            ],
            bases=('candidato.registro',),
        ),
    ]
