# Generated by Django 3.2.6 on 2021-08-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0007_auto_20210830_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_1',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel_2',
            field=models.BigIntegerField(blank=True),
        ),
    ]
